### ISSUE TITLE
Calculo da peça científica extra não funcionando muito bem

### ISSUE THREAD

**Issue by bettker** [dmag-ufsm/Game#10]
Obtive um caso em que não foi escolhida nenhuma peça, tendo a carta Scientists Guild.

O jogador possuía 2 compass, 1 gear e 0 tablets e estava com 5 VPs científicos (4 dos compass e 1 do gear), quando deveria ter ganhado 1 tablet e somado 13 VPs (4 dos compass, 1 do gear, 1 do tablet e 7 por 1 set completo).

Acredito que tenha que mudar a lógica do trecho que trata disso (player.cpp, lin 827-857).

**Comment by pprobst** [comment]
Creio ter achado o problema.

Veja as linhas 813-814 de `player.cpp`, no método `Player::CalculateScientificScore()`:
```
for (DMAG::Card const& card : this->cards_played) {
    if (card.GetType() != CARD_TYPE::scientific)
        continue;
    ...
```
E agora compare com o último `case` na linha 836, que está dentro do mesmo `for`:
```
    ...
    case CARD_ID::scientists:
        sci_extra++; break;
    }
}
```
Percebeu o problema, né? O `for` pula uma iteração se a carta atual `card` não for científica. A carta da guilda dos cientistas (`CARD_ID::scientists`) é do tipo `guild` e não `scientific`. Basta alterar o `if` para resolver o problema.

O fix já foi upado.

Caso o problema persistir por algum motivo, reabrir o issue.
