### ISSUE TITLE
Recursos com valor negativo

### ISSUE THREAD

**Issue by pprobst** [dmag-ufsm/Game#5]
Algumas vezes, recursos ficam com valores negativos.

**Comment by pprobst** [comment]
Nunca consegui replicar esse problema, então provavelmente foi arrumado. Reabrir este issue caso o problema ressurgir.

**Comment by pprobst** [comment]
Reaberto pois o @bettker ainda está achando esse erro.

**Comment by bettker** [comment]
Print do estado do jogo: https://i.imgur.com/ers3Um8.png (papyrus do jogador 0)

Não vi em que momento e com quais ações fez negativar, só percebi no final do jogo.
Se eu conseguir reproduzir novamente atualizo aqui.

**Comment by pprobst** [comment]
Aparentemente apenas os **recursos produzidos pelas maravilhas** estão ficando negativos.

**Comment by pprobst** [comment]
Fixed.
